-- =========================================================================
-- DATABASE INITIAL SCHEMA MIGRATION FOR HABITAT
-- Target: Supabase PostgreSQL
-- =========================================================================

-- Enable UUID extension if not already loaded
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. PROFILES TABLE
-- Extended user info linked to Supabase auth.users
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    timezone TEXT DEFAULT 'Asia/Karachi',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);


-- 2. HABIT MODULES TABLE
-- Each habit a user is tracking, generated by AI
CREATE TABLE IF NOT EXISTS public.habit_modules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    habit_name TEXT NOT NULL,
    goal_description TEXT,
    why_it_matters TEXT,
    blockers TEXT[],
    daily_plan JSONB, -- Array of {day: integer, task: text, tip: text}
    obstacle_playbook JSONB, -- Array of {trigger: text, response: text}
    env_design_tips TEXT[],
    phase INT DEFAULT 1, -- 1=high, 2=moderate, 3=reducing, 4=tapering, 5=autonomous
    status TEXT DEFAULT 'active', -- 'active' | 'autonomous' | 'completed' | 'restarted'
    streak_count INT DEFAULT 0,
    start_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on habit_modules
ALTER TABLE public.habit_modules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own habits" ON public.habit_modules
    FOR ALL USING (auth.uid() = user_id);


-- 3. DAILY LOGS TABLE
-- User marks daily completion for each habit module
CREATE TABLE IF NOT EXISTS public.daily_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    module_id UUID REFERENCES public.habit_modules(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    log_date DATE NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(module_id, log_date)
);

-- Enable RLS on daily_logs
ALTER TABLE public.daily_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own daily logs" ON public.daily_logs
    FOR ALL USING (auth.uid() = user_id);


-- 4. REMINDERS TABLE
-- Scheduled reminder records with tapering phase
CREATE TABLE IF NOT EXISTS public.reminders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    module_id UUID REFERENCES public.habit_modules(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    content TEXT NOT NULL,
    phase INT, -- Matches habit_modules.phase
    delivered BOOLEAN DEFAULT FALSE,
    snoozed BOOLEAN DEFAULT FALSE,
    snooze_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on reminders
ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own reminders" ON public.reminders
    FOR ALL USING (auth.uid() = user_id);


-- 5. CHECKINS TABLE
-- Day 21-25 AI check-in conversations and decisions
CREATE TABLE IF NOT EXISTS public.checkins (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    module_id UUID REFERENCES public.habit_modules(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    checkin_day INT, -- e.g. 21, 25
    user_response TEXT,
    ai_decision TEXT, -- 'close' | 'extend' | 'restart'
    ai_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on checkins
ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own checkins" ON public.checkins
    FOR ALL USING (auth.uid() = user_id);


-- 6. CHAT MESSAGES TABLE
-- Intake interview conversation history per habit
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    module_id UUID REFERENCES public.habit_modules(id) ON DELETE CASCADE, -- Nullable for initial intake before module creation
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    role TEXT NOT NULL, -- 'user' | 'assistant'
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on chat_messages
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own chat messages" ON public.chat_messages
    FOR ALL USING (auth.uid() = user_id);
